repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0  # Use the ref you want to point at
    hooks:
    - id: black
      language_version: python3  # Should match the python version you're using
